language: ruby
rvm:
  - "2.1.2"
script: 
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - mysql -e 'create database niupiao_rails'
  - psql -c 'create database niupiao_rails' -U postgres