default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: niu
  password:

development:
  <<: *default
  database: niu_dev

test:
  <<: *default
  database: niu_test

production:
  <<: *default
  database: niu_production
