# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a40e80666a164451f6ef9cfce67ca740e4abab68578b516c48b1cddfda6daf17a71ec42fc208ec3c9e3edeaf7b53100ef3800ee1b4b63cacabb3d491b3ca2e2

test:
  secret_key_base: 7b16524a225a7f47535c7a8e7bee40395667b309e334ebc91a7cd9974f8a8aefe411ba32cef0aec619cc6670e1091282ac70761fca90ac15bd711367c92db47f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
